target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  
  pod 'FirebaseAnalytics', '10.23.0'
  pod 'FirebaseCrashlytics', '10.23.0'
  pod 'FirebasePerformance', '10.23.0'
  pod 'FirebaseRemoteConfig', '10.23.0'
  pod 'FirebaseMessaging', '10.23.0'
end
